name: tipitaka-pali-reader
version: 1.1.0
summary: Tipitaka Pali Reader
description: Tipitaka Pali Reader Application


confinement: strict
base: core20
grade: stable
icon:  snap/gui/icon.png

slots:
  dbus-tipitaka-pali-reader: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.paauk.tipitaka_pali_reader # adjust accordingly to your app name and
    
apps:
  tipitaka-pali-reader:
    command: tipitaka-pali-reader
    extensions: [flutter-stable] # Where "stable" defines which Flutter channel to use for the build
    plugs:
    - network
    - desktop
    slots:
      - dbus-tipikata-pali-reader
parts:
  tipikata-pali-reader:
    source: .
    plugin: nil
    flutter-target: lib/main.dart # The main entry-point file of the application