name: tipitaka-pali-reader
version: 0.1.0
summary: Tipitaka Pali Reader
description: Tipitaka Pali Reader Application

confinement: strict
base: core18
grade: stable

slots:
  dbus-tipitaka-pali-reader: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.paauk.tipitaka_pali_reader # adjust accordingly to your app name and
    
apps:
  tipitaka-pali-reader:
    command: tipitaka_pali_reader
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-tipikata-pali-reader
parts:
  tipikata-pali-reader:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application