name: Build on Ubuntu 22.04

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl git unzip xz-utils zip libglu1-mesa \
            clang cmake ninja-build pkg-config libgtk-3-dev \
            libstdc++-12-dev libfuse2

      - name: Prepare assets directory
        run: mkdir -p assets/database

      - name: Download zip file
        run: |
          curl -L -o assets/database/tipitaka_pali.zip \
          "https://www.dropbox.com/scl/fi/lxgggckhlelifwhqcqx10/tipitaka_pali.zip?rlkey=la4fmcaabgr3163rhua537f4p&st=id2xyu5n&dl=1"

      - name: Extract zip file
        run: unzip -o assets/database/tipitaka_pali.zip -d assets/database/

      - name: Delete zip file
        run: rm -f assets/database/tipitaka_pali.zip

      - name: Run split.sh script inside assets/database
        run: |
          cd assets/database
          chmod +x split.sh
          sh split.sh

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter build (Linux)
        run: |
          flutter pub get
          flutter build linux --release

      - name: Make build_appimage2.sh executable
        run: chmod +x build_appimage2.sh

      - name: Build AppImage via script
        run: ./build_appimage2.sh

      - name: Extract AppImage
        run: |
          ./tipitaka_pali_reader.AppImage --appimage-extract
          mv squashfs-root TPR-Bundle
          chmod +x TPR-Bundle/tipitaka_pali_reader || true

      - name: Upload Linux unpacked AppImage bundle
        uses: actions/upload-artifact@v4
        with:
          name: TPR-Bundle
          path: TPR-Bundle

      - name: Upload Linux build bundle
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: tipitaka_pali_reader.AppImage
