name: Run TPR Builds Manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: 3.10.x

      # Install additional tools
      - name: Install additional tools
        run: |
          sudo apt update
          sudo apt install p7zip-full p7zip-rar unzip python-pip -y
          pip install gdown

      # Download the zip file using gdown
      - name: Download zip file
        run: gdown https://drive.google.com/uc?export=download&id=1II8XYSQw0JzZxJk2J4QT9XyN2SnqT9qm -O assets/database/tipitaka_pali.zip

      # Extract the zip file
      - name: Extract zip file
        run: unzip assets/database/tipitaka_pali.zip -d assets/database/

      # Delete the original zip file
      - name: Delete zip file
        run: rm assets/database/tipitaka_pali.zip

      # Run the split.sh script
      - name: Run split.sh script
        run: bash assets/database/split.sh

      # Flutter build for Linux and Android
      - name: Build Flutter project (Linux and Android)
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter pub get
          flutter build apk --release # For Android
          flutter build linux --release # For Linux
