name: Build Windows (MSIX)

on:
  workflow_dispatch:

jobs:
  build-windows-msix:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build Windows (Release)
        run: |
          flutter pub get
          flutter build windows --release

      - name: Download extra DLLs
        run: |
          curl -L -o dlls.tar.gz "https://www.dropbox.com/scl/fi/snreunqjw24o14erk369l/dlls.tar.gz?rlkey=yu93hvb4l4zf8jl1wv6vuftxk&st=hxvd9iwa&dl=1"
          tar -xzf dlls.tar.gz -C build/windows/runner/Release

      - name: Create MSIX (unsigned)
        run: flutter pub run msix:create

      - name: Upload MSIX
        uses: actions/upload-artifact@v4
        with:
          name: windows-msix
          path: |
            **/*.msix
            build/windows/**/*.msix

      - name: Upload Windows Release folder
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release
